#!/usr/bin/env bash
set -euo pipefail

DESTINATION="/opt/router/scripts/vpniplist.txt"

ASNS=(
13335   # Cloudflare
32934   # Meta
62041   # Telegram
13414   # X
)

mkdir -p "$(dirname "$DESTINATION")"

TMP=$(mktemp)

trap 'rm -f "$TMP"' EXIT

echo "# Generated by vpn-ip-update.sh $(date)" > "$TMP"
echo >> "$TMP"

for ASN in "${ASNS[@]}"; do
    echo "Fetching AS$ASN..."

    curl -fsSL \
    "https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS$ASN" |
    jq -r '.data.prefixes[].prefix' |
    grep -E '^[0-9]+\.' \
    >> "$TMP"

done

COUNT=$(grep -c '/' "$TMP" || true)

if [ "$COUNT" -lt 10 ]; then
    echo "ERROR: Prefix list too small ($COUNT entries)"
    exit 1
fi

sort -u "$TMP" > "${DESTINATION}.new"

mv "${DESTINATION}.new" "$DESTINATION"

sudo /opt/router/scripts/vpn-policy-route.sh

echo
echo "Saved to $DESTINATION"
echo "Total IPv4 prefixes: $(grep -c '/' "$DESTINATION")"
